name: C CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtest-dev cmake

    - name: Build Google Test
      run: |
        cd /usr/src/gtest
        sudo mkdir build
        cd build
        sudo cmake ..
        sudo make
        sudo cp lib/*.a /usr/lib

    - name: Build project
      run: |
        mkdir build
        cd build
        cp ../CMakeLists.txt .  # Copy CMakeLists.txt into the build directory
        cmake .
        make

    - name: Run tests
      run: |
        cd build
        ./test_runner